on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - name: Set Build Env
        run: |
          {
            echo "BUILD_TIME=$(date -u +%Y%m%d%H%M)"
            echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}"
            echo "MAGIC=$(git rev-parse --short HEAD || echo "GitNotFound")"
          } >> "$GITHUB_ENV"
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "gofwd"
          extra_files: LICENSE README.md
          executable_compression: "upx"
          ldflags: "-s -w -extldflags '-static' -X main.magic=${{ env.MAGIC }} -X 'main.date=${{ env.BUILD_TIME }}'"